import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

const DOMAIN_MAP: Record<string, string> = {
  'openai': 'https://openai.com',
  'meta-platforms-inc': 'https://about.meta.com',
  'xai': 'https://x.ai',
  'google-gemini': 'https://gemini.google.com',
  'anthropic': 'https://anthropic.com',
  'youtube': 'https://youtube.com',
  'lovable': 'https://lovable.dev',
  'z-ai': 'https://z.ai',
  'duolingo': 'https://duolingo.com',
  'discord': 'https://discord.com',
  'adobe': 'https://adobe.com',
  'google': 'https://google.com',
  'agentrouter': 'https://agentrouter.com',
  'cursor': 'https://cursor.com',
  'google-antigravity': 'https://antigravity.google',
  'higgsfield-ai': 'https://higgsfield.ai',
  'qoder': 'https://qoder.ai',
  'spotify-ab': 'https://spotify.com',
  'civo': 'https://civo.com',
  'apple': 'https://apple.com',
  'pixverse-ai': 'https://pixverse.ai',
  'miro': 'https://miro.com',
  'google-workspace': 'https://workspace.google.com',
  'kiro': 'https://kiro.ai',
  'vercel': 'https://vercel.com',
  'minimax': 'https://minimaxi.com',
  'elevenlabs': 'https://elevenlabs.io',
  'vultr': 'https://vultr.com',
  'merlin-ai': 'https://getmerlin.in',
  'oracle-corporation': 'https://oracle.com',
  'amazon': 'https://amazon.com',
  'wispr-ai-inc': 'https://wispr.ai',
  'perplexity-ai': 'https://perplexity.ai',
  'cloudflare': 'https://cloudflare.com',
  'browser-use-inc': 'https://browser-use.com',
  'manus-ai': 'https://manus.im',
  'shutterstock': 'https://shutterstock.com',
  'bolt-new': 'https://bolt.new',
  'figma': 'https://figma.com',
  'openart': 'https://openart.ai',
  'microsoft': 'https://microsoft.com',
  'github': 'https://github.com',
  'nordvpn': 'https://nordvpn.com',
  'canva': 'https://canva.com',
  'digitalocean': 'https://digitalocean.com',
  'notion': 'https://notion.so',
  'xiaomi': 'https://mi.com',
  'emergent-sh': 'https://emergent.sh',
  'zed-dev': 'https://zed.dev',
  'udemy': 'https://udemy.com',
  'spaceship-inc': 'https://spaceship.com',
  'meshy-ai': 'https://meshy.ai',
  'blink-new': 'https://blink.new',
  'lucid-software': 'https://lucidchart.com',
  'cloudways': 'https://cloudways.com',
  'modal': 'https://modal.com',
  'zoho': 'https://zoho.com',
  'linkedin': 'https://linkedin.com',
  'preply-inc': 'https://preply.com',
  'craft-do': 'https://craft.do',
  'aws': 'https://aws.amazon.com',
  'alibaba-cloud': 'https://alibabacloud.com',
  'multcloud': 'https://multcloud.com',
  'krea-ai-inc': 'https://krea.ai',
  'base44': 'https://base44.com',
  'notegpt-inc': 'https://notegpt.io',
  'runwayml': 'https://runwayml.com',
  'generic': 'https://paradox.engineer',
  'kaggle': 'https://kaggle.com',
  'shapr3d': 'https://shapr3d.com',
  'meta': 'https://meta.com',
  'suno': 'https://suno.com',
  'circleco-inc': 'https://circle.so',
  'google-cloud': 'https://cloud.google.com',
  'you-com': 'https://you.com',
  'malwarebytes': 'https://malwarebytes.com',
  'namecheap': 'https://namecheap.com',
  'asana-inc': 'https://asana.com',
  'mistral-ai': 'https://mistral.ai',
  'pcloud': 'https://pcloud.com',
  'airtable': 'https://airtable.com',
  'y-combinator': 'https://ycombinator.com',
  'upcloud': 'https://upcloud.com',
  'aerolink': 'https://aerolink.io',
  'replit': 'https://replit.com',
  'grammarly': 'https://grammarly.com',
  'trae': 'https://trae.ai',
  'akamai': 'https://akamai.com',
  'wasmer-pro': 'https://wasmer.io',
  'gearup-booster': 'https://gearupbooster.com',
  'sentry': 'https://sentry.io',
  'ovhcloud': 'https://ovhcloud.com',
  'toggle-vpn': 'https://toggle.pro',
  'tableau': 'https://tableau.com',
  'godaddy': 'https://godaddy.com',
  'atlassian': 'https://atlassian.com',
  'heygen': 'https://heygen.com',
  'jotform-inc': 'https://jotform.com',
  'parallel-ai': 'https://parallel.ai',
  'tencent-cloud': 'https://intl.cloud.tencent.com',
  'unity-technologies': 'https://unity.com',
  '37signals-llc': 'https://37signals.com',
  'framer': 'https://framer.com',
  'granola': 'https://granola.ai',
  'hostgator': 'https://hostgator.com',
  'kimi': 'https://kimi.moonshot.cn',
  'autodesk': 'https://autodesk.com',
  'vidu-ai': 'https://vidu.studio',
  'jasper-ai': 'https://jasper.ai',
  'mega-limited': 'https://mega.io',
  'coursera-inc': 'https://coursera.org',
  'microsoft-corporation': 'https://microsoft.com',
  'hashicorp': 'https://hashicorp.com',
  'ibm': 'https://ibm.com',
  'cloudflare-inc': 'https://cloudflare.com',
  'netlify': 'https://netlify.com',
  'kit-inc': 'https://kit.com',
  'quillbot': 'https://quillbot.com',
  '1password': 'https://1password.com',
  'deepgram': 'https://deepgram.com',
  'microsoft-azure': 'https://azure.microsoft.com',
  'overleaf': 'https://overleaf.com',
  'descript': 'https://descript.com',
  'grass-io': 'https://getgrass.io',
  'jio': 'https://jio.com',
  'sketch': 'https://sketch.com',
  'coderabbit': 'https://coderabbit.ai',
  'databricks': 'https://databricks.com',
  'heroku': 'https://heroku.com',
  'veed': 'https://veed.io',
  'mongodb': 'https://mongodb.com',
  'jetbrains': 'https://jetbrains.com',
  'seaart-ai': 'https://seaart.ai',
  'morphic-inc': 'https://morphic.sh',
  'otter-ai': 'https://otter.ai',
  'softorbits': 'https://softorbits.net',
  'lcn': 'https://lcn.com',
  'koofr': 'https://koofr.eu',
  'proton-ag': 'https://proton.me',
  'raycast': 'https://raycast.com',
  'slack': 'https://slack.com',
  'pipedrive': 'https://pipedrive.com',
  'scite-ai': 'https://scite.ai',
  'oxlo-ai': 'https://oxlo.ai',
  'hyper3d': 'https://hyper3d.ai',
  'writesonic': 'https://writesonic.com',
  'consensus': 'https://consensus.app',
  'udio-uncharted-labs': 'https://udio.com',
  'murf-ai': 'https://murf.ai',
  'reclaim-ai': 'https://reclaim.ai',
  'hulu-disney': 'https://hulu.com',
  'paperpal': 'https://paperpal.com',
  'headspace': 'https://headspace.com',
  'squarespace': 'https://squarespace.com',
  'softr': 'https://softr.io',
  'sync-com': 'https://sync.com',
};

async function seed() {
  const jsonPath = path.join(__dirname, 'resourify-brands.json');
  const raw = fs.readFileSync(jsonPath, 'utf-8');
  const brands: Array<{ slug: string; name: string }> = JSON.parse(raw);

  console.log(`Starting upsert of ${brands.length} brands...`);

  let count = 0;
  for (const b of brands) {
    const website = DOMAIN_MAP[b.slug] || `https://${b.slug.replace(/-inc|-corporation|-llc|-ab|-ag/g, '')}.com`;
    const domain = website.replace(/https?:\/\//, '').split('/')[0];
    const logoUrl = `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

    await prisma.brand.upsert({
      where: { slug: b.slug },
      update: {
        name: b.name,
        website,
        logoUrl,
      },
      create: {
        name: b.name,
        slug: b.slug,
        website,
        logoUrl,
      },
    });
    count++;
  }

  const totalInDb = await prisma.brand.count();
  console.log(`Successfully upserted ${count} brands! Total in DB: ${totalInDb}`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
