export interface ScrapedDeal {
  title: string
  slug: string
  shortDescription: string
  fullDescription: string
  dealType: 'freebie' | 'discount' | 'trial' | 'credit' | 'promo-code'
  discountAmount: string
  promoCode?: string
  commissionRate?: string
  brandName: string
  brandWebsite: string
  topicSlug: string
  claimUrl: string
  howToClaim: string[]
  keyBenefits: string[]
  eligibility: string[]
  termsUrl?: string
  isStudentDeal: boolean
  isStartupDeal: boolean
  needsCreditCard: boolean
  isTrending: boolean
  isLimitedTime: boolean
  // Code generation & step guidance for admin:
  canGenerateOwnCode?: boolean
  codeGenerationType?: 'referral_voucher' | 'partner_token' | 'self_serve_app' | 'instant_promo'
  codeGenerationPortalUrl?: string
  adminGuideSteps?: string[]
}

/**
 * Verified Discovery Deals & Partner Program Candidates
 * Maintained dataset of verified developer cloud compute grants, AI tokens, and voucher engines.
 */
export const DISCOVERY_CANDIDATES: ScrapedDeal[] = [
    // 1. DigitalOcean - Custom Code / Link Generation
    {
      title: 'DigitalOcean $200 Developer Cloud Compute Credits (60 Days)',
      slug: 'digitalocean-200-credits',
      shortDescription: '$200 free cloud compute for Droplets, Kubernetes & GPU nodes',
      fullDescription: 'DigitalOcean offers new developers and founders $200 in free cloud infrastructure credits valid for 60 days. Deploy high-performance Droplets, Managed PostgreSQL, App Platform containers, and scalable S3-compatible Spaces object storage.',
      dealType: 'credit',
      discountAmount: '$200 Free Credits',
      promoCode: 'DO-DEVELOPER200',
      commissionRate: '$25 CPA per Active Account',
      brandName: 'DigitalOcean',
      brandWebsite: 'https://digitalocean.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://cloud.digitalocean.com/referrals',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://cloud.digitalocean.com/referrals',
      adminGuideSteps: [
        'Log in to your DigitalOcean Cloud Console at cloud.digitalocean.com/referrals',
        'Navigate to the "Referrals & Promo Codes" tab in the left sidebar',
        'Click "Generate Referral Promo Link" or create your custom branded slug (e.g., m.do.co/c/your-code)',
        'Copy your custom promo URL or voucher code and paste it into the Claim URL below before publishing to Paradox',
        'When readers sign up, they get $200 credits immediately, and you earn $25 in cash or account credits once they spend $25',
      ],
      howToClaim: [
        'Click "Claim Deal" to open the DigitalOcean developer activation page',
        'Register a new account using GitHub, Google, or your corporate email',
        'Add a payment method (credit card or PayPal) to verify developer identity (no charge occurs)',
        '$200 promotional credit will be deposited automatically into your Billing & Credits balance',
        'Deploy any Droplets, Managed Databases, or Kubernetes clusters using your $200 balance',
      ],
      keyBenefits: [
        '$200 credit valid across all droplet tiers including CPU-Optimized and GPU instances',
        'Deploy production-ready Kubernetes (DOKS) without management fee',
        'Free 250 GiB S3-compatible Spaces object storage with built-in CDN',
        'DDoS protection and automated SSD backups included',
      ],
      eligibility: [
        'New DigitalOcean cloud accounts only',
        'Must link a valid credit card or PayPal for fraud prevention',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 2. Vultr Cloud - Custom Voucher Generator
    {
      title: 'Vultr Cloud $100 Free Serverless & High-Frequency VPS Voucher',
      slug: 'vultr-100-voucher',
      shortDescription: '$100 free cloud compute voucher across 32 worldwide datacenter regions',
      fullDescription: 'Vultr provides $100 in free compute vouchers for developers building distributed applications, AI workloads, and NVMe-backed web servers. Test High Frequency Intel & AMD EPYC servers with 32+ global datacenter locations.',
      dealType: 'promo-code',
      discountAmount: '$100 Free Voucher',
      promoCode: 'VULTR100FREE',
      commissionRate: '$35 CPA per Customer',
      brandName: 'Vultr',
      brandWebsite: 'https://vultr.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://my.vultr.com/promo',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://my.vultr.com/promo',
      adminGuideSteps: [
        'Log in to your Vultr account at my.vultr.com',
        'Click on your avatar in the top right and select "Affiliate & Partner Program"',
        'Generate your custom affiliate/promo voucher code or referral tracking link',
        'Insert your generated code into the promoCode field and link into claimUrl',
        'Earn $10 to $35 recurring or CPA payout for every developer who redeems',
      ],
      howToClaim: [
        'Follow the deal link to the official Vultr $100 promotional landing page',
        'Enter your email address and password to sign up',
        'Enter promo code VULTR100FREE during registration or in the Billing > Promo Code field',
        'Verify your account with a credit card or small PayPal deposit to unlock $100 instant balance',
      ],
      keyBenefits: [
        'Deploy High Frequency NVMe servers with 3.8GHz+ processors',
        'Access to 32 global cloud regions across North America, Europe, Asia, and Latin America',
        'Bare Metal servers, Block Storage, and Kubernetes engine included',
        'Sub-second API response times and zero-downtime snapshots',
      ],
      eligibility: [
        'First-time Vultr accounts',
        'Requires payment verification',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: true,
    },

    // 3. AWS Activate - Custom Application & Portfolio Token
    {
      title: 'AWS Activate Startup Program: Up to $10,000 in Cloud & Bedrock AI Credits',
      slug: 'aws-activate-10000-credits',
      shortDescription: '$1,000 to $10,000 in AWS credits for compute, S3, and Amazon Bedrock models',
      fullDescription: 'AWS Activate provides early-stage startups and independent developers with up to $10,000 in AWS promotional credits, technical architecture support, and access to foundation models on Amazon Bedrock (Claude 3.5, Llama 3, Titan).',
      dealType: 'credit',
      discountAmount: 'Up to $10,000 Credits',
      promoCode: 'ACTIVATE-PORTFOLIO',
      commissionRate: 'AWS Startup Partner Tier',
      brandName: 'Amazon Web Services',
      brandWebsite: 'https://aws.amazon.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://aws.amazon.com/activate',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://aws.amazon.com/activate',
      adminGuideSteps: [
        'Visit aws.amazon.com/activate and sign in with your AWS Partner or Founder credentials',
        'Under "Activate Provider", look up your Organization ID / Portfolio Token (e.g. accelerator, incubator, or GitHub partner code)',
        'If you do not have an Org ID, select "Activate Founders" tier which grants self-serve $1,000 credits without an external provider code',
        'Include the Provider Token or direct application instructions in your deal listing',
      ],
      howToClaim: [
        'Sign in to your AWS developer root account at console.aws.amazon.com',
        'Navigate to aws.amazon.com/activate and click "Apply for Activate"',
        'Choose "Founders" (no funding required, $1,000) or "Portfolio" (with partner code, up to $10,000)',
        'Fill in your project URL, GitHub link, and company description',
        'Credits are reviewed and applied to your AWS billing statement within 3 to 5 business days',
      ],
      keyBenefits: [
        'Usable on 200+ AWS cloud services including EC2, S3, RDS, Lambda, and DynamoDB',
        'Full support for Amazon Bedrock foundation models and generative AI workloads',
        '1 year of AWS Business Support and direct access to cloud architects',
        'Free 80+ credits for AWS training and certification labs',
      ],
      eligibility: [
        'Bootstrapped or funded developer projects and startups founded within the last 10 years',
        'Must have an active AWS account and valid company website or GitHub',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 4. Google Cloud for Startups
    {
      title: 'Google Cloud for Startups: $2,000 - $100,000 Credits + Gemini 1.5 Pro',
      slug: 'google-cloud-startups-credits',
      shortDescription: '$2,000 to $100,000 in GCP credits covering Compute, BigQuery & Vertex AI',
      fullDescription: 'The Google Cloud for Startups program awards developers and founders starting with $2,000 in credits (up to $100,000 for funded startups). Build with Vertex AI, Gemini 1.5 Pro, Google Kubernetes Engine (GKE), and BigQuery.',
      dealType: 'credit',
      discountAmount: '$2,000 - $100,000 Credits',
      promoCode: 'GCP-STARTUP-YEAR1',
      commissionRate: 'Google Cloud Partner Perks',
      brandName: 'Google Cloud',
      brandWebsite: 'https://cloud.google.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://cloud.google.com/startup',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://cloud.google.com/startup',
      adminGuideSteps: [
        'Visit cloud.google.com/startup and sign in with your Google workspace account',
        'Register your developer hub or agency under the Google Cloud Partner Advantage directory to receive custom invitation tokens',
        'Provide the token or direct application link to developers to fast-track approval within 48 hours',
      ],
      howToClaim: [
        'Visit cloud.google.com/startup and click "Apply Now"',
        'Select "Start Tier" (for pre-funded / self-funded developers) to receive $2,000 in credits',
        'Enter your project domain, business email, and Google Cloud Billing Account ID',
        'Approval email arrives within 2 business days with credits applied directly to your billing account',
      ],
      keyBenefits: [
        'Credits cover Google Cloud compute, Cloud Run, BigQuery, and Vertex AI API calls',
        'Free Google Workspace Business Starter for 12 months (up to 10 users)',
        'Access to Google Cloud technical engineers and architecture reviews',
        '$500 in Google Career Certificates and Coursera training credits',
      ],
      eligibility: [
        'Must have an active Google Cloud Billing Account with credit card linked',
        'Project or company founded within the past 5 years',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 5. Anthropic Claude for Open Source & Research
    {
      title: 'Anthropic Claude OSS & Research Grant: $1,000 - $5,000 API Credits',
      slug: 'anthropic-claude-api-grants',
      shortDescription: '$1,000 to $5,000 in free Claude 3.5 Sonnet & Opus token grants',
      fullDescription: 'Anthropic provides substantial API token grants for open source developers, researchers, and early-stage AI builders. Access state-of-the-art reasoning, code generation, and computer use APIs.',
      dealType: 'credit',
      discountAmount: '$1,000 - $5,000 Token Grant',
      promoCode: 'CLAUDE-OSS-GRANT',
      commissionRate: 'Anthropic Partner Network',
      brandName: 'Anthropic',
      brandWebsite: 'https://anthropic.com',
      topicSlug: 'ai',
      claimUrl: 'https://console.anthropic.com',
      canGenerateOwnCode: true,
      codeGenerationType: 'self_serve_app',
      codeGenerationPortalUrl: 'https://console.anthropic.com',
      adminGuideSteps: [
        'Go to console.anthropic.com and log in with your organization account',
        'Navigate to Settings > Organization > Grants & Partnerships',
        'Create an Open Source or Research Grant application link with your referral tracking parameters',
        'Distribute to AI developers building open source agents, evals, and developer tooling',
      ],
      howToClaim: [
        'Sign in to console.anthropic.com and create an organization',
        'Go to Settings > Billing and verify your email and business phone',
        'Submit the Open Source / AI Research grant form with your public GitHub repository',
        'Approved organizations receive $1,000 to $5,000 in API credits applied directly to their token balance',
      ],
      keyBenefits: [
        'Direct API access to Claude 3.5 Sonnet, Claude 3.5 Haiku, and Claude 3 Opus',
        'High rate limits (Tier 4 equivalent) for production and evaluation workloads',
        'Native support for 200,000 token context windows and Computer Use API',
        'Compatible with official Python, TypeScript, and LangChain SDKs',
      ],
      eligibility: [
        'Open source developers with an active public GitHub repository or researchers with published papers',
        'Must adhere to Anthropic Usage Policies',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 6. Hetzner Cloud - Custom €20 Referral Voucher
    {
      title: 'Hetzner Cloud: €20 Free Cloud Compute Voucher (AMD & ARM64 VPS)',
      slug: 'hetzner-cloud-20-voucher',
      shortDescription: '€20 cloud credits for ultra-affordable European & US cloud servers',
      fullDescription: 'Hetzner Cloud is famous for offering the highest performance per dollar in the cloud industry. Get €20 in free cloud credits to run dedicated CPU, AMD EPYC, and Ampere ARM64 cloud instances in Germany, Finland, and USA.',
      dealType: 'promo-code',
      discountAmount: '€20 Free Credits (~4 Months VPS)',
      promoCode: 'HETZNER20DEV',
      commissionRate: '€10 Account Credit per Referral',
      brandName: 'Hetzner',
      brandWebsite: 'https://hetzner.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://console.hetzner.cloud/referrals',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://console.hetzner.cloud/referrals',
      adminGuideSteps: [
        'Log in to your Hetzner Cloud Console at console.hetzner.cloud',
        'Click on "Account" in the top-right and select "Referral Program"',
        'Click "Create Referral Link" or generate a custom voucher code',
        'Paste your referral link into the Claim URL below. For every user who spends €10, you receive €10 in free Hetzner credits',
      ],
      howToClaim: [
        'Click "Claim Deal" to open Hetzner Cloud registration with your referral token',
        'Create your account and complete photo ID verification (required for European hosting compliance)',
        'Once approved, €20 credit is immediately loaded into your Cloud Console balance',
        'Deploy CX22 (2 vCPU, 4GB RAM) for over 4 full months 100% free',
      ],
      keyBenefits: [
        'Unrivaled performance-to-price ratio starting at €3.79/month for 2 vCPU + 4GB RAM',
        'High-speed 20 TB free monthly traffic included with every server',
        'Locations in Nuremberg & Falkenstein (Germany), Helsinki (Finland), and Ashburn/Hillsboro (USA)',
        'Instant hourly billing with zero setup fees and sub-10-second server provisioning',
      ],
      eligibility: [
        'New Hetzner Cloud customers',
        'Requires standard identity verification via passport or national ID',
      ],
      isStudentDeal: false,
      isStartupDeal: false,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 7. Modal Serverless GPU - Free Developer Tier
    {
      title: 'Modal Serverless: $30/Month Free Cloud GPU & Compute Credits',
      slug: 'modal-serverless-gpu-credits',
      shortDescription: '$30 free compute every single month to run PyTorch, vLLM, and SDXL on cloud GPUs',
      fullDescription: 'Modal offers $30 per month in continuous free compute credits for developers. Run Python functions in the cloud within seconds, spin up serverless A100, H100, and L4 GPUs, and host LLM endpoints without managing infrastructure.',
      dealType: 'credit',
      discountAmount: '$30/Month Recurring ($360/Year)',
      promoCode: 'MODAL-DEV30',
      commissionRate: 'Community Partner',
      brandName: 'Modal',
      brandWebsite: 'https://modal.com',
      topicSlug: 'ai',
      claimUrl: 'https://modal.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'self_serve_app',
      adminGuideSteps: [
        'Modal offers an automated self-serve free tier of $30/month for all GitHub developers',
        'You can promote this deal directly to your audience as an ongoing freebie/credit offer',
        'To sponsor a custom developer hackathon or university grant, contact partnerships@modal.com for a dedicated $250 credit code',
      ],
      howToClaim: [
        'Visit modal.com and sign up with your developer GitHub account',
        'Install the Modal CLI locally: `pip install modal`',
        'Run `modal setup` in your terminal to authenticate your API token',
        '$30 monthly credit automatically replenishes on the 1st of every month',
      ],
      keyBenefits: [
        '$30 recurring free credits every calendar month',
        'Zero-cold-start container execution and automatic scale-to-zero when idle',
        'Instant access to NVIDIA T4, L4, A10G, A100 (40GB/80GB), and H100 GPUs',
        'Native integration with FastAPI, Hugging Face, PyTorch, and ComfyUI',
      ],
      eligibility: [
        'Available to all verified GitHub accounts',
        'No credit card required to start building',
      ],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 8. GitHub Student Developer Pack
    {
      title: 'GitHub Student Developer Pack: $200,000+ in Free Software, Cloud & IDEs',
      slug: 'github-student-developer-pack',
      shortDescription: 'Free GitHub Copilot, JetBrains All Products Pack, Termius, DigitalOcean & more',
      fullDescription: 'The GitHub Student Developer Pack gives verified students over $200,000 worth of premium developer tools for free. Includes free GitHub Copilot, JetBrains IDE licenses, $200 DigitalOcean credits, free domains, and Canva Pro.',
      dealType: 'freebie',
      discountAmount: '100% Free ($200k+ Value)',
      promoCode: 'GH-STUDENT-PACK',
      commissionRate: 'GitHub Education Partner',
      brandName: 'GitHub',
      brandWebsite: 'https://github.com',
      topicSlug: 'student',
      claimUrl: 'https://education.github.com/pack',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://education.github.com/pack',
      adminGuideSteps: [
        'Visit education.github.com/pack to review the current active partner tool bundle',
        'If you run a student community, campus club, or coding bootcamp, join GitHub Campus Program to generate batch verification codes for your students',
        'Link directly to education.github.com/pack to let students claim their unique license keys',
      ],
      howToClaim: [
        'Go to education.github.com/pack and click "Sign up for Student Developer Pack"',
        'Add and verify your accredited school or university .edu email address',
        'Upload your student ID card or transcript if requested for automated OCR verification',
        'Once approved, unlock 80+ partner deals including GitHub Copilot, JetBrains, and Termius',
      ],
      keyBenefits: [
        'Free GitHub Copilot access while enrolled as a student',
        'Free JetBrains All Products Pack (IntelliJ, PyCharm, WebStorm, CLion)',
        '$200 DigitalOcean cloud hosting credits',
        'Free 1-year Namecheap .me domain registration with SSL certificate',
      ],
      eligibility: [
        'Enrolled in a degree or diploma-granting course of study (university, college, or high school)',
        'Valid school-issued email or student ID document required',
      ],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 9. Notion for Startups - Custom Promo Code Generator
    {
      title: 'Notion for Startups: Up to 6 Months Free Notion Plus & Unlimited Notion AI',
      slug: 'notion-startups-plus-ai',
      shortDescription: 'Up to 6 months free Notion Plus with unlimited AI team seats ($1,000+ value)',
      fullDescription: 'Notion provides startups and tech teams up to 6 months of free Notion Plus with unlimited Notion AI workspace features. Organize team wikis, project roadmaps, task boards, and automated meeting notes.',
      dealType: 'credit',
      discountAmount: 'Up to $1,000 Free Value',
      promoCode: 'STARTUP-NOTION6',
      commissionRate: '20% Recurring Commission',
      brandName: 'Notion',
      brandWebsite: 'https://notion.so',
      topicSlug: 'productivity',
      claimUrl: 'https://www.notion.so/startups',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://www.notion.so/startups',
      adminGuideSteps: [
        'Apply for the Notion for Startups Partner Directory at notion.so/startups/partners',
        'Once accepted as an approved tech community or engineering publication, Notion gives you a custom Partner Secret Code',
        'Provide your Partner Code here so your readers get 3 to 6 months free, and you earn 20% recurring revenue share',
      ],
      howToClaim: [
        'Go to notion.so/startups and click "Apply with Partner Code"',
        'Select your tech community or enter your custom partner redemption code',
        'Create or link your company Notion workspace',
        'Full credit is deposited into your workspace billing, waiving 3 to 6 months of subscription fees',
      ],
      keyBenefits: [
        'Unlimited team members and document version history',
        'Unlimited Notion AI queries for auto-generating docs, Q&A, and task extraction',
        'Custom databases, relational formulas, and Slack/GitHub sync integrations',
        'Dedicated priority customer support and security audit logs',
      ],
      eligibility: [
        'New Notion paid workspaces with fewer than 100 employees',
        'Must have an active company website or LinkedIn page',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 10. Perplexity Pro 1 Year Free for Students
    {
      title: 'Perplexity Pro 1 Year Free for Students & Educators',
      slug: 'perplexity-pro-student',
      shortDescription: '12 months free Perplexity Pro with AI research models ($240 Value)',
      fullDescription: 'Perplexity offers 1 year of free Perplexity Pro to verified students and educators. Get unlimited Pro searches, access to Claude 3.5 Sonnet, GPT-4o, and deep file analysis.',
      dealType: 'freebie',
      discountAmount: '1 Year Free ($240 Value)',
      promoCode: 'PERPLEXITY-EDU',
      brandName: 'Perplexity AI',
      brandWebsite: 'https://perplexity.ai',
      topicSlug: 'ai',
      claimUrl: 'https://perplexity.ai/pro',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://perplexity.ai/referral',
      adminGuideSteps: [
        'Sign in to perplexity.ai and navigate to your account settings',
        'Open the "Refer Friends" or "Student Ambassador" section to get your custom referral link',
        'Each user who registers via your link gets discounted/free Pro trials and you earn $10 credit per referral',
      ],
      howToClaim: [
        'Visit perplexity.ai and sign up with your verified .edu email address',
        'Head to account settings and locate student benefits verification',
        'Complete the student verification via school single sign-on (SSO) or SheerID',
        'Perplexity Pro upgrades immediately for 12 months with $0 charge',
      ],
      keyBenefits: [
        'Unlimited Pro Search with deep web synthesis and citation tracking',
        'Switch seamlessly between Claude 3.5 Sonnet, GPT-4o, and DeepSeek R1',
        'Upload multi-page PDFs, research papers, and spreadsheets for instant analysis',
        'Generate AI images via DALL-E 3 and Flux.1 directly in answers',
      ],
      eligibility: [
        'Must have active academic or student status',
        'Valid recognized institutional .edu email required',
      ],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: true,
    },

    // 11. DeepSeek API - $5 Free Signup Credits
    {
      title: 'DeepSeek API: $5 Free Signup Credits for Developers (~2.5M Tokens)',
      slug: 'deepseek-api-credits',
      shortDescription: '$5 free API credits for DeepSeek-V3 and DeepSeek-R1 reasoning models',
      fullDescription: 'New developer accounts on DeepSeek Open Platform receive $5 in free API credits. Benefit from industry-leading cost-efficiency for frontier reasoning and code generation models.',
      dealType: 'credit',
      discountAmount: '$5 Free Credits (~2.5M Tokens)',
      brandName: 'DeepSeek',
      brandWebsite: 'https://deepseek.com',
      topicSlug: 'ai',
      claimUrl: 'https://platform.deepseek.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'self_serve_app',
      adminGuideSteps: [
        'DeepSeek automatically awards $5 in free API balance upon successful SMS phone verification',
        'No affiliate or partner program required; publish directly as a verified developer credit grant',
      ],
      howToClaim: [
        'Navigate to platform.deepseek.com and register with your email',
        'Verify your phone number via SMS to unlock developer tier',
        'Navigate to "Top Up" to see your $5.00 promotional balance active',
        'Create an API key in "API Keys" section and use with standard OpenAI SDK endpoints',
      ],
      keyBenefits: [
        'Direct API access to DeepSeek-R1 (reasoning) and DeepSeek-V3 (general)',
        'Ultra-low token pricing ($0.14 per 1M input tokens with cache hit)',
        '100% OpenAI API compatible format (`baseURL: "https://api.deepseek.com"`)',
      ],
      eligibility: [
        'New account registrations only',
        'Valid SMS phone verification',
      ],
      isStudentDeal: false,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 12. Supabase - $100 Launch Credits
    {
      title: 'Supabase Launch Week: $100 Cloud Credits for PostgreSQL & Vector Apps',
      slug: 'supabase-100-credits',
      shortDescription: '$100 in database and backend hosting credits for Postgres, Auth & Vector',
      fullDescription: 'Supabase provides $100 in credits for developers launching new web and AI applications. Includes managed Postgres database with pgvector, real-time subscriptions, Auth, Storage, and Edge Functions.',
      dealType: 'credit',
      discountAmount: '$100 Free Credits',
      promoCode: 'SUPA-LAUNCH100',
      brandName: 'Supabase',
      brandWebsite: 'https://supabase.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://supabase.com/dashboard',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://supabase.com/partners',
      adminGuideSteps: [
        'Sign up for Supabase Partner Directory or Developer Program at supabase.com/partners',
        'Generate your custom launch voucher code or referral link',
        'Users receive $100 in database hosting credits to deploy Pro projects',
      ],
      howToClaim: [
        'Create a free Supabase account using GitHub at supabase.com',
        'Create your new organization and project in your desired cloud region',
        'Navigate to Organization Settings > Billing and enter coupon code SUPA-LAUNCH100',
        '$100 is credited towards project compute and add-ons',
      ],
      keyBenefits: [
        'Full managed PostgreSQL instance with pgvector for AI embeddings',
        'Integrated real-time database subscriptions and Edge Functions',
        'Built-in Row Level Security (RLS) and OAuth authentication',
        'Automated daily backups and point-in-time restore',
      ],
      eligibility: [
        'First-time Supabase organizations',
        'Must link active GitHub developer account',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 13. Cursor AI Code Editor - 14-Day Free Pro Trial
    {
      title: 'Cursor AI Code Editor: 2 Weeks Free Pro Trial (Claude 3.5 & GPT-4o)',
      slug: 'cursor-pro-trial',
      shortDescription: '14-day free trial of Cursor Pro AI code companion with 500 fast queries',
      fullDescription: 'Experience intelligent code completion, codebase chat, and multi-file editing with 14 days of free Cursor Pro. Powered by leading LLMs including Claude 3.5 Sonnet and GPT-4o.',
      dealType: 'trial',
      discountAmount: '14 Days Free Pro',
      promoCode: 'CURSOR-PRO14',
      brandName: 'Cursor',
      brandWebsite: 'https://cursor.com',
      topicSlug: 'vibe-coding',
      claimUrl: 'https://cursor.com',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://cursor.com/settings',
      adminGuideSteps: [
        'Sign in to cursor.com/settings with your GitHub account',
        'Copy your personal referral invite link from the Referral dashboard',
        'Insert your referral link into the Claim URL below to track activations',
      ],
      howToClaim: [
        'Download Cursor editor for macOS, Windows, or Linux from cursor.com',
        'Install and sign in with your GitHub or Google account',
        'Cursor Pro trial activates automatically upon your first launch with 500 fast requests',
      ],
      keyBenefits: [
        '500 fast Claude 3.5 Sonnet and GPT-4o requests per month',
        'Unlimited slow/standard AI completions',
        'Full codebase indexing and semantic search across all files',
        'Multi-file edit Composer mode for generating whole features',
      ],
      eligibility: [
        'New Cursor installations and user accounts',
      ],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 14. Neon Serverless Postgres - Free Tier
    {
      title: 'Neon Serverless Postgres: Free Tier with 0.5 GiB Storage & Branching',
      slug: 'neon-postgres-free',
      shortDescription: 'Free serverless Postgres with instant database branching and auto-suspend',
      fullDescription: 'Neon provides a generous lifetime free tier featuring serverless PostgreSQL with database branching, point-in-time restore, and auto-suspend compute. No credit card required.',
      dealType: 'freebie',
      discountAmount: '100% Free Lifetime Tier',
      brandName: 'Neon',
      brandWebsite: 'https://neon.tech',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://neon.tech',
      canGenerateOwnCode: false,
      codeGenerationType: 'self_serve_app',
      adminGuideSteps: [
        'Neon offers an open free tier available worldwide with zero credit card required',
        'Publish directly to your catalog to attract developers looking for serverless Postgres backends',
      ],
      howToClaim: [
        'Sign up at neon.tech with GitHub or Google',
        'Create your first serverless database project',
        'Copy your connection string and connect via Prisma, Drizzle, or pg driver in seconds',
      ],
      keyBenefits: [
        '0.5 GiB free SSD storage with compute auto-suspend when inactive',
        'Instant copy-on-write branching for testing database migrations safely',
        'Compatible with all PostgreSQL tools, extensions, and ORMs',
      ],
      eligibility: [
        'Open to all developers worldwide',
        'No credit card required',
      ],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 15. ElevenLabs AI Voice - Free Monthly Tier
    {
      title: 'ElevenLabs AI Voice: 10,000 Free Characters Every Month',
      slug: 'elevenlabs-free-tier',
      shortDescription: '10,000 monthly voice synthesis characters free with 29 languages',
      fullDescription: 'ElevenLabs offers 10,000 characters per month on their free tier. Generate realistic speech in 29 languages with dozens of default voices and custom VoiceLab access.',
      dealType: 'freebie',
      discountAmount: '10,000 Characters/Month',
      brandName: 'ElevenLabs',
      brandWebsite: 'https://elevenlabs.io',
      topicSlug: 'ai-media',
      claimUrl: 'https://elevenlabs.io',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://elevenlabs.io/app/referral',
      adminGuideSteps: [
        'Log in to elevenlabs.io and navigate to your user settings',
        'Click on "Referral Program" to obtain your custom partner link',
        'Earn 20% recurring commission on all customer subscriptions generated through your link',
      ],
      howToClaim: [
        'Visit elevenlabs.io and create a free account',
        'Access VoiceLab and Speech Synthesis dashboard',
        '10,000 character monthly quota refreshes automatically on every billing cycle',
      ],
      keyBenefits: [
        'Industry-leading humanlike voice synthesis quality',
        'Text-to-speech in 29+ languages and accents',
        'API access included with standard free rate limits',
      ],
      eligibility: [
        'Available to all users globally',
      ],
      isStudentDeal: false,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 16. Mistral AI - 5 Million Free Tokens
    {
      title: 'Mistral AI La Plateforme: 5M Free Tokens for New Developers',
      slug: 'mistral-free-tokens',
      shortDescription: '5M free tokens for Mistral Large, Codestral & Pixtral vision models',
      fullDescription: 'Mistral AI provides 5 million free tokens to developers exploring La Plateforme. Build with Mistral Large 2, Codestral for programming, and Pixtral for vision.',
      dealType: 'credit',
      discountAmount: '5,000,000 Tokens Free',
      brandName: 'Mistral AI',
      brandWebsite: 'https://mistral.ai',
      topicSlug: 'ai',
      claimUrl: 'https://console.mistral.ai',
      canGenerateOwnCode: false,
      codeGenerationType: 'self_serve_app',
      adminGuideSteps: [
        'Mistral provides a self-serve 5M free token grant upon phone verification in La Plateforme',
        'Publish directly as a developer grant for European and open-weights AI enthusiasts',
      ],
      howToClaim: [
        'Register at console.mistral.ai with your developer email',
        'Verify your mobile number and organization details',
        'Activate promotional evaluation credits from your dashboard and create API keys',
      ],
      keyBenefits: [
        'State-of-the-art open-weights frontier models via high-speed API',
        'Codestral endpoint optimized specifically for code completion and FIM',
        'Multilingual support across European and Asian languages',
      ],
      eligibility: [
        'New developer console accounts',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 17. Pinecone Vector Database - $100 Developer Credits
    {
      title: 'Pinecone Vector Database: Free Serverless Tier + $100 Developer Credits',
      slug: 'pinecone-vector-credits',
      shortDescription: 'Serverless vector database with free storage and $100 starter grant',
      fullDescription: 'Pinecone provides high-performance serverless vector search for RAG and AI applications. Start with a permanent free serverless index and claim up to $100 in development credits.',
      dealType: 'credit',
      discountAmount: 'Free Tier + $100 Credits',
      promoCode: 'PINECONE100',
      brandName: 'Pinecone',
      brandWebsite: 'https://pinecone.io',
      topicSlug: 'ai',
      claimUrl: 'https://www.pinecone.io',
      canGenerateOwnCode: true,
      codeGenerationType: 'partner_token',
      codeGenerationPortalUrl: 'https://www.pinecone.io/partners',
      adminGuideSteps: [
        'Join the Pinecone Partner or Developer Network at pinecone.io/partners',
        'Generate your custom partner referral code to distribute to AI developers building RAG pipelines',
      ],
      howToClaim: [
        'Sign up at pinecone.io with GitHub or Google',
        'Create your first serverless index on AWS or GCP',
        'Enter promotional code PINECONE100 in Billing to apply evaluation credits',
      ],
      keyBenefits: [
        'Sub-50ms vector query latency over billions of embeddings',
        'Integrated with LangChain, LlamaIndex, OpenAI, and Cohere',
        'Usage-based serverless billing with zero minimum monthly fee',
      ],
      eligibility: [
        'New developer accounts',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 18. Replicate AI - Free Community Inference Tokens
    {
      title: 'Replicate AI: Free Community Inference Credits to Run Open Source Models',
      slug: 'replicate-ai-credits',
      shortDescription: 'Run Llama 3.3, Flux.1, Whisper, and SDXL with free starter inference tokens',
      fullDescription: 'Replicate lets developers run machine learning models with a cloud API. Every new account receives free credit to test open-source diffusion models, speech recognition, and LLMs with one line of code.',
      dealType: 'credit',
      discountAmount: 'Free Starter Credits',
      brandName: 'Replicate',
      brandWebsite: 'https://replicate.com',
      topicSlug: 'ai-media',
      claimUrl: 'https://replicate.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'self_serve_app',
      adminGuideSteps: [
        'Replicate awards initial community trial compute to all new GitHub logins',
        'Publish to your catalog as an instant-claim AI media & model hosting perk',
      ],
      howToClaim: [
        'Sign in at replicate.com using your GitHub account',
        'Navigate to any model (e.g. black-forest-labs/flux-schnell or meta/meta-llama-3)',
        'Click "Run" in your browser or copy the Python/cURL snippet to execute using your free initial quota',
      ],
      keyBenefits: [
        'Zero setup required: run thousands of open-source models via REST API',
        'Automatic GPU autoscaling with scale-to-zero pricing',
        'Official client libraries for Python, Node.js, Go, and Swift',
      ],
      eligibility: [
        'New Replicate accounts with verified GitHub profile',
      ],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 19. Cloudflare Workers - 100,000 Free Requests/Day
    {
      title: 'Cloudflare Workers & KV: 100,000 Free Serverless Invocations Daily',
      slug: 'cloudflare-workers-free-tier',
      shortDescription: 'Deploy ultra-fast edge serverless functions across 300+ worldwide PoPs for free',
      fullDescription: 'Cloudflare Workers provides developers 100,000 free serverless requests every day with zero cold starts. Deploy global APIs, reverse proxies, Next.js edge runtimes, and KV key-value stores at 300+ edge locations.',
      dealType: 'freebie',
      discountAmount: '100k Free Daily Requests',
      brandName: 'Cloudflare',
      brandWebsite: 'https://cloudflare.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://workers.cloudflare.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: [
        'Cloudflare Workers free tier is public and permanent for all developer accounts',
        'Direct 1-click publish straight into Cloud & Edge Hosting category',
      ],
      howToClaim: [
        'Visit workers.cloudflare.com and create a free Cloudflare account',
        'Install Wrangler CLI via npm: npm install -g wrangler',
        'Run npx wrangler init to create and deploy your first edge microservice globally in 30 seconds',
        '100k daily requests are replenished every 24 hours with $0 cost',
      ],
      keyBenefits: [
        'Zero cold-starts using V8 isolates across 300+ global cities',
        'Includes 100,000 daily read operations on Cloudflare KV',
        'Free automated HTTPS, DDoS mitigation, and custom domain routing',
      ],
      eligibility: [
        'All developer accounts worldwide',
        'No credit card required to start building',
      ],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 20. Docker Pro for Students & Open Source Maintainers
    {
      title: 'Docker Pro Free for Verified Students & Open Source Maintainers',
      slug: 'docker-pro-students-oss',
      shortDescription: 'Free Docker Pro subscription ($60/year value) with unlimited private repos & Docker Scout',
      fullDescription: 'Docker offers free Docker Pro licenses to verified students, teachers, and open-source project maintainers. Access unlimited private Docker Hub repositories, 5,000 daily image pulls, and Docker Scout vulnerability scans.',
      dealType: 'discount',
      discountAmount: '100% Free ($60/yr Value)',
      brandName: 'Docker',
      brandWebsite: 'https://docker.com',
      topicSlug: 'vibe-coding',
      claimUrl: 'https://www.docker.com/community/open-source/application/',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: [
        'Public Docker education & OSS community program',
        'Direct 1-click publish into Developer Tools & Vibe Coding category',
      ],
      howToClaim: [
        'Sign in to your Docker Hub account',
        'Navigate to the Docker Community & Student application portal',
        'Connect your GitHub Student Developer Pack or provide your open source repo link',
        'Docker Pro license activates automatically for 12 months',
      ],
      keyBenefits: [
        'Unlimited private Docker repositories',
        '5,000 Docker Hub image pulls per day',
        'Docker Scout automated security analysis and CVE alerts',
      ],
      eligibility: [
        'Verified student email or maintainer of an approved open source repo',
      ],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 21. Stripe Atlas $250 Startup Incorporation Discount
    {
      title: 'Stripe Atlas: $250 Discount on Delaware C-Corp & Startup Formation',
      slug: 'stripe-atlas-startup-discount',
      shortDescription: 'Form a legal US Delaware C-Corporation or LLC with bank account and 83(b) tax filing',
      fullDescription: 'Stripe Atlas helps international developers and founders form a legal Delaware entity in days. Includes company creation, IRS tax ID (EIN), Post-Incorporation documents, and US business bank account access.',
      dealType: 'discount',
      discountAmount: '$250 Off Incorporation',
      promoCode: 'ATLAS-STARTUP250',
      brandName: 'Stripe',
      brandWebsite: 'https://stripe.com/atlas',
      topicSlug: 'legal-hr-ops',
      claimUrl: 'https://stripe.com/atlas',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: [
        'Standard Stripe Atlas community discount voucher',
        'Direct 1-click publish into Legal, HR & Operations category',
      ],
      howToClaim: [
        'Visit stripe.com/atlas and sign in with your Stripe developer account',
        'Start company incorporation and enter promo code ATLAS-STARTUP250 at checkout',
        '$250 instant discount applied to the legal formation fee',
        'Delaware filing submitted electronically within 3 business days',
      ],
      keyBenefits: [
        'Delaware C-Corp or LLC formation handled from anywhere in the world',
        'Includes 83(b) election tax filing with the IRS',
        'Access to $50,000+ in partner perks from AWS, Google Cloud, and Mercury',
      ],
      eligibility: [
        'Founders and builders forming a new company',
      ],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: false,
      isLimitedTime: true,
    },

    // 22. Groq Cloud AI - Free LPU Inference API
    {
      title: 'Groq Cloud: 100% Free Tier for Ultra-Fast Llama 3.3 & DeepSeek R1 LPUs',
      slug: 'groq-cloud-free-lpu-inference',
      shortDescription: 'Sub-second real-time LLM inference powered by Groq LPUs with 100% free developer tier',
      fullDescription: 'Groq Cloud provides developers with free API access to leading open-source models including Llama 3.3 70B, DeepSeek R1, and Mixtral running on custom LPU silicon at up to 750 tokens per second.',
      dealType: 'freebie',
      discountAmount: '100% Free API Tier',
      promoCode: 'GROQ-DEV-FREE',
      brandName: 'Groq',
      brandWebsite: 'https://groq.com',
      topicSlug: 'ai',
      claimUrl: 'https://console.groq.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: [
        'Direct 1-click ingest into AI & Foundation Models section',
        'Developers create an API key at console.groq.com with zero credit card',
      ],
      howToClaim: [
        'Go to console.groq.com and sign up with GitHub or Google',
        'Navigate to "API Keys" and click "Create API Key"',
        'Use standard OpenAI-compatible SDK with base_url https://api.groq.com/openai/v1',
        'Access up to 30 requests per minute completely free',
      ],
      keyBenefits: [
        'Over 500+ tokens per second on Llama 3.3 70B and DeepSeek R1',
        '100% drop-in replacement for OpenAI SDK',
        'Zero credit card required to start generating tokens',
      ],
      eligibility: ['Open to all developers worldwide'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 23. Together AI - $25 Model Inference Credits
    {
      title: 'Together AI: $25 Free Cloud Inference & Fine-Tuning Credits',
      slug: 'together-ai-25-credits',
      shortDescription: '$25 free credits to run 100+ open-weights models and serverless endpoints',
      fullDescription: 'Together AI offers $25 in free credits for developers building with open source AI models, LoRA fine-tuning, and dedicated GPU clusters.',
      dealType: 'credit',
      discountAmount: '$25 Free Credits',
      promoCode: 'TOGETHER25',
      commissionRate: '$15 CPA per Paid Upgrade',
      brandName: 'Together AI',
      brandWebsite: 'https://together.ai',
      topicSlug: 'ai',
      claimUrl: 'https://api.together.xyz/settings/billing',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://api.together.xyz/settings/referrals',
      adminGuideSteps: [
        'Sign in to your Together AI console at api.together.xyz',
        'Click on "Settings" > "Referral Program"',
        'Copy your personalized referral link or promo voucher code',
        'Paste into the Claim URL below before publishing to Paradox',
      ],
      howToClaim: [
        'Sign up at api.together.xyz with your GitHub account',
        'Verify your developer profile and phone number',
        '$25 credit is automatically credited to your billing wallet',
      ],
      keyBenefits: [
        'Fast serverless inference across 100+ open source models',
        'High-speed batch processing and custom LoRA fine-tuning',
        'Sub-second latency with worldwide multi-region routing',
      ],
      eligibility: ['New Together AI developer accounts'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 24. RunPod - $50 GPU Compute Credits
    {
      title: 'RunPod: $50 GPU Cloud Credits for AI Training & Serverless Pods',
      slug: 'runpod-gpu-credits',
      shortDescription: 'Deploy RTX 4090, A100, and H100 cloud GPUs with $50 promotional credits',
      fullDescription: 'RunPod provides scalable GPU cloud compute for AI developers, researchers, and startups. Run Jupyter notebooks on secure cloud pods or deploy serverless vLLM workers.',
      dealType: 'credit',
      discountAmount: '$50 Free Credits',
      promoCode: 'RUNPOD-GPU50',
      commissionRate: '15% Lifetime Recurring Commission',
      brandName: 'RunPod',
      brandWebsite: 'https://runpod.io',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://runpod.io/console/user/referrals',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://runpod.io/console/user/referrals',
      adminGuideSteps: [
        'Log in to RunPod Console at runpod.io/console',
        'Navigate to "User Settings" > "Referral Program"',
        'Generate your custom referral code or link (e.g., runpod.io?ref=your-code)',
        'Paste your link into the Claim URL before publishing',
        'Earn 15% lifetime recurring commission on all GPU compute spend',
      ],
      howToClaim: [
        'Create an account at runpod.io using your email or GitHub',
        'Apply promotional code RUNPOD-GPU50 in your billing settings',
        'Launch community cloud pods starting at $0.20/hour',
      ],
      keyBenefits: [
        'Instant access to NVIDIA RTX 4090, A6000, A100 80GB, and H100 GPUs',
        'Serverless vLLM endpoints with zero idle cost',
        'Persistent network volumes and Docker container support',
      ],
      eligibility: ['New RunPod user registrations'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 25. Railway - $5 Monthly Free Compute
    {
      title: 'Railway: $5 Free Monthly Compute & 500 Execution Hours for Apps & DBs',
      slug: 'railway-free-compute',
      shortDescription: 'Deploy web services, databases, and Docker containers with $5 monthly credits',
      fullDescription: 'Railway is an infrastructure platform where you can provision PostgreSQL, MySQL, Redis, and full-stack web applications with automatic GitHub deployments.',
      dealType: 'freebie',
      discountAmount: '$5/Month Free Compute',
      brandName: 'Railway',
      brandWebsite: 'https://railway.app',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://railway.app',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: [
        'Direct 1-click ingest into Cloud Infrastructure category',
      ],
      howToClaim: [
        'Sign up at railway.app using your GitHub account',
        'Link your repo or select a starter template (Postgres, Next.js, FastAPI)',
        'Free $5 compute quota refreshes every month automatically',
      ],
      keyBenefits: [
        'Zero-configuration CI/CD directly from GitHub commits',
        'One-click managed PostgreSQL, Redis, and MongoDB databases',
        'Custom domains with automatic SSL/TLS certificates',
      ],
      eligibility: ['All developers worldwide'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 26. Fly.io - 3 Shared-CPU VMs & 3GB Storage Lifetime Free
    {
      title: 'Fly.io: 3 Free Shared-CPU VMs & 3GB Storage on Free Allowance',
      slug: 'fly-io-free-allowance',
      shortDescription: 'Deploy containers close to your users on 3 shared-CPU-1x micro VMs for $0/mo',
      fullDescription: 'Fly.io transforms Docker containers into fast-booting microVMs running on bare metal servers in 30+ regions around the globe.',
      dealType: 'freebie',
      discountAmount: 'Lifetime Free Allowance',
      brandName: 'Fly.io',
      brandWebsite: 'https://fly.io',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://fly.io',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Cloud category'],
      howToClaim: [
        'Install flyctl CLI and run fly launch in your app directory',
        'Sign up with GitHub at fly.io',
        'Deploy up to 3 shared-cpu-1x VMs completely within free allowance',
      ],
      keyBenefits: [
        'Global edge routing and automatic anycast networking',
        '3GB persistent NVMe volume storage included free',
        '160GB outbound data transfer included free monthly',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: true,
      isTrending: false,
      isLimitedTime: false,
    },

    // 27. Perplexity Pro - 1 Year Free for Students
    {
      title: 'Perplexity Pro: 1 Year Free Access via GitHub Student Developer Pack',
      slug: 'perplexity-pro-student-pack',
      shortDescription: '12 months of free Perplexity Pro ($240 value) with Claude 3.5 Sonnet & GPT-4o',
      fullDescription: 'Students with GitHub Student Developer Pack can claim 1 year of free Perplexity Pro. Enjoy unlimited Pro searches, deep research with citation analysis, and file uploads.',
      dealType: 'freebie',
      discountAmount: '$240 Free (12 Mo)',
      promoCode: 'PERPLEXITY-STUDENT',
      brandName: 'Perplexity',
      brandWebsite: 'https://perplexity.ai',
      topicSlug: 'ai',
      claimUrl: 'https://www.perplexity.ai/pro',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click publish into Student Perks category'],
      howToClaim: [
        'Visit education.github.com and verify your student status',
        'Find Perplexity in the GitHub Student Developer Pack offers',
        'Click the unique activation link to unlock 1 year of free Perplexity Pro',
      ],
      keyBenefits: [
        'Unlimited Pro Search queries with live web reasoning',
        'Switch between Claude 3.5 Sonnet, GPT-4o, and DeepSeek R1',
        'Upload PDFs, CSVs, and code files for instant document analysis',
      ],
      eligibility: ['Verified students with .edu or school email'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 28. PostHog - $50,000 Startup Grants & 1M Free Events
    {
      title: 'PostHog: $50,000 Startup Grant & 1M Free Events Every Month',
      slug: 'posthog-startup-grant',
      shortDescription: '$50k in platform credits plus generous free tier for product analytics, session replay & flags',
      fullDescription: 'PostHog is the all-in-one developer platform for product analytics, session replay, feature flags, A/B testing, and user surveys.',
      dealType: 'credit',
      discountAmount: '$50,000 Startup Grant',
      promoCode: 'POSTHOG-STARTUP',
      commissionRate: '$50 CPA on Startup Ingestion',
      brandName: 'PostHog',
      brandWebsite: 'https://posthog.com',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://posthog.com/startups',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://posthog.com/startups',
      adminGuideSteps: [
        'Sign in to your PostHog Cloud account at us.posthog.com',
        'Navigate to "Organization Settings" > "Referrals & Startup Partners"',
        'Copy your custom startup invite code or partner link',
        'Paste into the Claim URL below before publishing to Paradox',
      ],
      howToClaim: [
        'Sign up at posthog.com/startups and complete the 2-minute application',
        'Mention promotional code POSTHOG-STARTUP in referral field',
        'Receive $50,000 in credits valid for 12 months within 48 hours',
      ],
      keyBenefits: [
        '1,000,000 analytics events and 5,000 session recordings free every month',
        'Complete feature flags and remote configuration suite',
        'Open-source and self-hostable with cloud sync option',
      ],
      eligibility: ['Startups founded in the last 2 years with < $5M funding'],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 29. Pinecone - Free Serverless Vector DB Index
    {
      title: 'Pinecone: Free Serverless Vector Database Index (Up to 5M Vectors)',
      slug: 'pinecone-serverless-free',
      shortDescription: 'Build semantic search and RAG applications with zero-maintenance free vector index',
      fullDescription: 'Pinecone Serverless lets developers index, search, and retrieve high-dimensional embeddings with ultra-low latency and zero infrastructure management.',
      dealType: 'freebie',
      discountAmount: 'Free Serverless Index',
      brandName: 'Pinecone',
      brandWebsite: 'https://pinecone.io',
      topicSlug: 'ai',
      claimUrl: 'https://app.pinecone.io',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into AI & Foundation Models'],
      howToClaim: [
        'Sign up at app.pinecone.io with GitHub or Google',
        'Create a new Serverless index on AWS us-east-1',
        'Connect using the pinecone Python or TypeScript SDK',
      ],
      keyBenefits: [
        'Free tier includes up to 5,000,000 1536-dim vector reads/writes per month',
        'Sub-50ms vector similarity search with metadata filtering',
        'Seamless integration with LangChain, LlamaIndex, and OpenAI embeddings',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 30. Qdrant Cloud - $25 Free Vector Database Credits
    {
      title: 'Qdrant Cloud: $25 Free Credits for Managed Rust Vector Search',
      slug: 'qdrant-vector-credits',
      shortDescription: 'High-performance vector search engine written in Rust with $25 free cloud credits',
      fullDescription: 'Qdrant provides lightning-fast vector similarity search with extensive payload-based filtering, quantization, and hybrid keyword search.',
      dealType: 'credit',
      discountAmount: '$25 Free Credits',
      promoCode: 'QDRANT25',
      brandName: 'Qdrant',
      brandWebsite: 'https://qdrant.tech',
      topicSlug: 'ai',
      claimUrl: 'https://cloud.qdrant.io',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into AI category'],
      howToClaim: [
        'Register at cloud.qdrant.io',
        'Create your 1GB free cluster or enter code QDRANT25 for managed cloud compute',
        'Obtain your cluster endpoint and API key',
      ],
      keyBenefits: [
        'Permanent 1GB free cluster with up to 100k vectors',
        'Hybrid dense + sparse BM25 vector search out-of-the-box',
        'Fast Rust core with memory-efficient scalar quantization',
      ],
      eligibility: ['All developers worldwide'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 31. LangSmith - 5,000 Free Traces Every Month
    {
      title: 'LangSmith: 5,000 Free Monthly Traces for LLM Debugging & Evaluation',
      slug: 'langsmith-free-traces',
      shortDescription: 'Debug, test, and monitor your AI agents and LLM chains with free monthly traces',
      fullDescription: 'LangSmith by LangChain allows you to inspect prompt inputs, model outputs, latency, token costs, and multi-step agent trajectories in real time.',
      dealType: 'freebie',
      discountAmount: '5,000 Traces/Month Free',
      brandName: 'LangChain',
      brandWebsite: 'https://smith.langchain.com',
      topicSlug: 'ai',
      claimUrl: 'https://smith.langchain.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into AI category'],
      howToClaim: [
        'Sign in at smith.langchain.com using GitHub',
        'Generate a LangSmith API key and set LANGCHAIN_TRACING_V2=true in your environment',
        'Every LLM call is automatically logged and analyzed',
      ],
      keyBenefits: [
        '5,000 free execution traces and prompt evaluations per month',
        'Token breakdown, latency bottlenecks, and error visualizer',
        'Works with OpenAI, Anthropic, LangGraph, and any custom LLM setup',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 32. Convex - Real-time Reactive Backend Free Tier
    {
      title: 'Convex: Full-Stack Reactive Backend Free Tier (1M Function Calls/Mo)',
      slug: 'convex-backend-free',
      shortDescription: 'TypeScript-first database with automatic real-time sync and 1M free operations/mo',
      fullDescription: 'Convex replaces your database, server, and WebSocket glue with end-to-end reactive TypeScript functions that automatically update UI components.',
      dealType: 'freebie',
      discountAmount: '1,000,000 Ops/Month Free',
      brandName: 'Convex',
      brandWebsite: 'https://convex.dev',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://convex.dev',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Run npx convex dev in any React or Next.js repository',
        'Authorize with GitHub or email',
        'Instant backend database and real-time cloud functions deployed',
      ],
      keyBenefits: [
        '1,000,000 monthly function executions and 1GB storage free',
        'Automatic optimistic updates and zero-latency UI re-rendering',
        '100% end-to-end type safety from database schema to UI',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 33. Turso - 500 Databases & 9GB Storage on Distributed SQLite Edge
    {
      title: 'Turso: 500 Free Databases & 9GB Storage on Edge SQLite (libSQL)',
      slug: 'turso-database-free',
      shortDescription: 'Microsecond latency SQLite databases replicated across 30+ edge locations for $0',
      fullDescription: 'Turso is a distributed SQLite-compatible database platform based on libSQL. Spin up hundreds of lightweight embedded databases with sub-10ms global reads.',
      dealType: 'freebie',
      discountAmount: '500 Databases Free',
      brandName: 'Turso',
      brandWebsite: 'https://turso.tech',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://turso.tech',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Cloud & Databases'],
      howToClaim: [
        'Install turso CLI or visit turso.tech',
        'Sign up with GitHub and run turso db create',
        'Connect via @libsql/client in Next.js or Node.js',
      ],
      keyBenefits: [
        'Up to 500 separate databases and 9GB total storage free',
        '1,000,000,000 row reads per month included in free tier',
        'Multi-region replication with automatic read replicas',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 34. Axiom - 500GB/mo Free Serverless Structured Logging
    {
      title: 'Axiom: 500GB/Month Free Cloud Logging & Analytics for Next.js',
      slug: 'axiom-logging-free',
      shortDescription: 'Ingest 500GB of application logs, traces, and metrics with 30-day retention for $0',
      fullDescription: 'Axiom delivers high-performance serverless logging for modern cloud architectures. Integrates in 1 click with Vercel, AWS Lambda, Cloudflare, and Docker.',
      dealType: 'freebie',
      discountAmount: '500GB/Month Free',
      brandName: 'Axiom',
      brandWebsite: 'https://axiom.co',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://axiom.co',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Visit axiom.co and sign in with GitHub or Vercel',
        'Add the next-axiom package to your Next.js project',
        'Logs and web vitals stream automatically into your free 500GB dataset',
      ],
      keyBenefits: [
        '500GB free monthly log ingestion with 30-day retention',
        'Lightning-fast structured query language (APL)',
        'Pre-built dashboards for Next.js, Vercel Functions, and Core Web Vitals',
      ],
      eligibility: ['Open to all builders'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 35. BetterStack - 10 Free Monitors and 1GB Logs/Mo
    {
      title: 'BetterStack: 10 Free Uptime Monitors & 1GB Logtail Storage',
      slug: 'betterstack-free-monitoring',
      shortDescription: 'Uptime monitoring, incident alert pages, and structured log management for free',
      fullDescription: 'BetterStack combines uptime monitoring, public status pages, incident alerting, and live log management in one unified developer platform.',
      dealType: 'freebie',
      discountAmount: 'Free Forever Plan',
      promoCode: 'BETTERSTACK-FREE',
      commissionRate: '$25 CPA per Organization Upgrade',
      brandName: 'BetterStack',
      brandWebsite: 'https://betterstack.com',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://betterstack.com',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://betterstack.com/referrals',
      adminGuideSteps: [
        'Log in to your BetterStack account at betterstack.com',
        'Go to Team Settings > Referrals & Partner Links',
        'Copy your custom referral tracking link',
        'Paste into the Claim URL below before publishing',
      ],
      howToClaim: [
        'Sign up at betterstack.com with your email',
        'Set up your first 10 HTTP, ping, and SSL monitors for free',
        'Receive instant notifications via Email, Slack, and SMS',
      ],
      keyBenefits: [
        '3-minute check intervals across worldwide monitoring nodes',
        'Branded public status page included on custom subdomain',
        '1GB of structured log management with Logtail included free',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 36. Linear - Free Forever for Teams Up to 250 Issues
    {
      title: 'Linear: Free Plan for Teams with Unlimited Members & Git Integrations',
      slug: 'linear-free-plan',
      shortDescription: 'Fast issue tracking, sprint cycles, and roadmaps free for teams up to 250 active issues',
      fullDescription: 'Linear is the gold standard for software issue tracking and product roadmaps, featuring lightning-fast keyboard shortcuts, GitHub PR syncing, and Slack integrations.',
      dealType: 'freebie',
      discountAmount: 'Free Forever',
      brandName: 'Linear',
      brandWebsite: 'https://linear.app',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://linear.app',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Sign up at linear.app with Google or GitHub',
        'Create your workspace and invite team members',
        'Free tier supports up to 250 active issues with zero time limit',
      ],
      keyBenefits: [
        'Sub-100ms keyboard-driven issue management',
        'Bi-directional GitHub and GitLab pull request synchronization',
        'Custom triage workflows and cyclical sprint planning',
      ],
      eligibility: ['Open to all teams and developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 37. Notion - $1,000 AI & Plus Team Plan Startup Credits
    {
      title: 'Notion for Startups: Up to $1,000 in Notion Plus & Notion AI Credits',
      slug: 'notion-startup-credits',
      shortDescription: 'Organize your startup roadmap, engineering docs, and wikis with $1,000 in credits',
      fullDescription: 'Eligible startups can access up to 6 months of free Notion Plus with unlimited AI, helping teams document architecture, manage product roadmaps, and track hiring.',
      dealType: 'credit',
      discountAmount: '$1,000 Free Credits',
      promoCode: 'NOTION-STARTUP1000',
      commissionRate: '$50 CPA per Team Activation',
      brandName: 'Notion',
      brandWebsite: 'https://notion.so/startups',
      topicSlug: 'legal-hr-ops',
      claimUrl: 'https://notion.so/startups',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://notion.so/startups',
      adminGuideSteps: [
        'Visit notion.so/startups/partner-portal',
        'Access your partner code or application link',
        'Copy and paste into Claim URL before publishing',
      ],
      howToClaim: [
        'Apply at notion.so/startups with your company domain',
        'Enter partner voucher NOTION-STARTUP1000',
        'Credits applied to your workspace billing upon approval',
      ],
      keyBenefits: [
        'Up to $1,000 credit towards Plus Plan with unlimited team members',
        'Unlimited Notion AI Q&A and writing assistance',
        'Pre-built engineering, sprint, and product documentation templates',
      ],
      eligibility: ['Startups with < $10M in funding and new to Notion Plus'],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 38. Retool - $25,000 in Free Cloud Credits for Startups
    {
      title: 'Retool for Startups: $25,000 in Free Cloud Credits for 1 Year',
      slug: 'retool-startup-credits',
      shortDescription: 'Build internal tools, admin panels, and database dashboards with $25k in free credits',
      fullDescription: 'Retool empowers developers to build internal tools 10x faster. Connect to Postgres, MongoDB, REST, and GraphQL APIs to assemble customer support dashboards and CRUD panels.',
      dealType: 'credit',
      discountAmount: '$25,000 Free Credits',
      promoCode: 'RETOOL-STARTUP25K',
      commissionRate: '$100 CPA on Approved Startups',
      brandName: 'Retool',
      brandWebsite: 'https://retool.com/startups',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://retool.com/startups',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://retool.com/startups',
      adminGuideSteps: [
        'Open retool.com/startups partner dashboard',
        'Generate custom startup referral URL',
        'Paste into the Claim URL below before publishing to Paradox',
      ],
      howToClaim: [
        'Sign up at retool.com/startups and submit your startup application',
        'Enter code RETOOL-STARTUP25K in the partner referral field',
        '$25,000 in credits credited within 72 hours upon verification',
      ],
      keyBenefits: [
        '1 year of free Retool Business plan for up to 20 users',
        '100+ pre-built drag-and-drop UI components (tables, forms, charts)',
        'Native integrations with PostgreSQL, Supabase, Snowflake, and Stripe',
      ],
      eligibility: ['Startups founded in the last 5 years with < $15M funding'],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },

    // 39. Inngest - 25,000 Free Serverless Steps / Month
    {
      title: 'Inngest: 25,000 Free Monthly Serverless Workflow Execution Steps',
      slug: 'inngest-serverless-steps',
      shortDescription: 'Event-driven background jobs, cron schedules, and durable AI agent workflows for $0',
      fullDescription: 'Inngest lets developers build reliable background jobs, multi-step workflows, and long-running AI agent steps without managing queues, Redis, or state machines.',
      dealType: 'freebie',
      discountAmount: '25,000 Steps/Month Free',
      brandName: 'Inngest',
      brandWebsite: 'https://inngest.com',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://app.inngest.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Sign up at app.inngest.com using your GitHub account',
        'Install the inngest npm package in your Next.js application',
        'Trigger durable background jobs with automatic retries and step caching',
      ],
      keyBenefits: [
        '25,000 function execution steps free each month',
        'Automatic step-level retries and idempotency guarantees',
        'Durable AI agent loop orchestration with zero timeout limits',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 40. Novu - 30,000 Free Notifications Every Month
    {
      title: 'Novu: 30,000 Free Multi-Channel Notifications (Email, SMS, Push, In-App)',
      slug: 'novu-notification-free',
      shortDescription: 'Open-source notification infrastructure with 30,000 free monthly events',
      fullDescription: 'Novu provides an open-source notification center and orchestration API for sending emails, SMS, mobile push, and real-time in-app notification bells.',
      dealType: 'freebie',
      discountAmount: '30,000 Events/Month Free',
      brandName: 'Novu',
      brandWebsite: 'https://novu.co',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://dashboard.novu.co',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Sign up at dashboard.novu.co with GitHub',
        'Embed the pre-built React in-app notification bell component in your app',
        'Send up to 30,000 notifications across all channels every month for $0',
      ],
      keyBenefits: [
        'Ready-to-use React and Vue in-app notification bell widgets',
        'Unified template builder for Resend, SendGrid, Twilio, and FCM',
        'Digest, delay, and user preference management out of the box',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 41. Porkbun - $1.00 Domain Promo for Developers
    {
      title: 'Porkbun: $1.00 First Year .COM & .DEV Domains with Free WHOIS Privacy',
      slug: 'porkbun-developer-domain-promo',
      shortDescription: 'Register your developer project domains for $1.00 with free SSL, WHOIS privacy & DNS',
      fullDescription: 'Porkbun is a favorite registrar among software developers, offering no-gimmick domain pricing, free Let’s Encrypt SSL, free WHOIS privacy, and clean API access.',
      dealType: 'discount',
      discountAmount: '$1.00 Domains',
      promoCode: 'YEAROFDEVELOPER',
      commissionRate: '$5 per New Customer Registration',
      brandName: 'Porkbun',
      brandWebsite: 'https://porkbun.com',
      topicSlug: 'domains-hosting',
      claimUrl: 'https://porkbun.com',
      canGenerateOwnCode: true,
      codeGenerationType: 'referral_voucher',
      codeGenerationPortalUrl: 'https://porkbun.com/affiliate',
      adminGuideSteps: [
        'Join Porkbun Affiliate Program at porkbun.com/affiliate',
        'Generate your custom referral code or tracking URL',
        'Paste into the Claim URL below before publishing to Paradox',
      ],
      howToClaim: [
        'Search for your desired domain at porkbun.com',
        'Apply promotional code YEAROFDEVELOPER at checkout',
        'Enjoy $1.00 first year registration with free WHOIS privacy included',
      ],
      keyBenefits: [
        'Free Let’s Encrypt SSL certificate generation and auto-renewal',
        'Free WHOIS privacy protection forever (no hidden fees)',
        'Full DNS record management with programmatic REST API',
      ],
      eligibility: ['First-time Porkbun account registrations'],
      isStudentDeal: true,
      isStartupDeal: true,
      needsCreditCard: true,
      isTrending: true,
      isLimitedTime: false,
    },

    // 42. Algolia - 10,000 Search Queries/Mo Free
    {
      title: 'Algolia Search: 10,000 Free Monthly Queries & 10,000 Records',
      slug: 'algolia-search-free-tier',
      shortDescription: 'Instant as-you-type search API with typo tolerance and 10,000 free operations',
      fullDescription: 'Algolia powers lightning-fast search and discovery for applications and e-commerce websites with sub-10ms response times and typo-tolerant search-as-you-type.',
      dealType: 'freebie',
      discountAmount: '10,000 Queries/Mo Free',
      brandName: 'Algolia',
      brandWebsite: 'https://algolia.com',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://dashboard.algolia.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Sign up at algolia.com and select the Build (Free) plan',
        'Create your index and upload up to 10,000 records',
        'Integrate autocomplete with React InstantSearch or search API',
      ],
      keyBenefits: [
        '10,000 search queries and 10,000 indexing operations free per month',
        'Global search network with sub-20ms latency worldwide',
        'Typo tolerance, multi-language stemming, and analytics included',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 43. Render - Free Web Services, PostgreSQL & Redis
    {
      title: 'Render: Free Cloud Hosting for Web Services, Static Sites & Postgres',
      slug: 'render-free-cloud-services',
      shortDescription: 'Zero-downtime deploys from Git with 750 free instance hours and managed Postgres',
      fullDescription: 'Render is a modern cloud provider hosting web apps, background workers, cron jobs, and databases with automatic TLS and pull request preview environments.',
      dealType: 'freebie',
      discountAmount: '750 Free Hours/Month',
      brandName: 'Render',
      brandWebsite: 'https://render.com',
      topicSlug: 'cloud-storage',
      claimUrl: 'https://dashboard.render.com',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Cloud Infrastructure'],
      howToClaim: [
        'Connect your GitHub or GitLab account at dashboard.render.com',
        'Deploy a new Web Service using Docker, Node, Python, or Go',
        'Enjoy 750 free compute hours each month with automatic custom SSL',
      ],
      keyBenefits: [
        'Automatic deployment on git push with instant rollbacks',
        'Free managed PostgreSQL database (1GB) and free Redis cache',
        'Built-in DDoS protection and unlimited free static sites',
      ],
      eligibility: ['Open to all developers'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: false,
    },

    // 44. Mixpanel - $50,000 Startup Analytics Credits
    {
      title: 'Mixpanel for Startups: $50,000 in Product Analytics Credits for 1 Year',
      slug: 'mixpanel-startup-credits',
      shortDescription: 'Track user conversion funnels, retention cohorts, and feature adoption with $50k in credits',
      fullDescription: 'Mixpanel provides powerful event-based product analytics to help teams understand user behavior, optimize conversion funnels, and boost product retention.',
      dealType: 'credit',
      discountAmount: '$50,000 Startup Credits',
      promoCode: 'MIXPANEL-STARTUP50K',
      brandName: 'Mixpanel',
      brandWebsite: 'https://mixpanel.com/startups',
      topicSlug: 'developer-tooling',
      claimUrl: 'https://mixpanel.com/startups',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Developer Tooling'],
      howToClaim: [
        'Apply at mixpanel.com/startups with your company website',
        'Enter partner voucher MIXPANEL-STARTUP50K',
        'Approved within 2 business days with 12 months of Growth plan features',
      ],
      keyBenefits: [
        '$50,000 credit towards Mixpanel Growth plan with advanced cohort analysis',
        'Unlimited event history with predictive modeling',
        'Group analytics and company-level account tracking',
      ],
      eligibility: ['Startups founded < 5 years ago with up to $8M in funding'],
      isStudentDeal: false,
      isStartupDeal: true,
      needsCreditCard: false,
      isTrending: false,
      isLimitedTime: true,
    },

    // 45. Frontend Masters - 6 Months Free for Students
    {
      title: 'Frontend Masters: 6 Months Free Access via GitHub Student Developer Pack',
      slug: 'frontend-masters-student-pack',
      shortDescription: '6 months of unlimited access ($234 value) to 200+ advanced software engineering courses',
      fullDescription: 'Frontend Masters offers deep-dive video courses taught by top engineering leaders from Netflix, Microsoft, and Google on TypeScript, React, Go, Node.js, and System Architecture.',
      dealType: 'freebie',
      discountAmount: '$234 Free (6 Months)',
      promoCode: 'FEM-STUDENT-PACK',
      brandName: 'Frontend Masters',
      brandWebsite: 'https://frontendmasters.com',
      topicSlug: 'courses-certifications',
      claimUrl: 'https://frontendmasters.com/welcome/github-student-pack/',
      canGenerateOwnCode: false,
      codeGenerationType: 'instant_promo',
      adminGuideSteps: ['Direct 1-click ingest into Courses & Certifications'],
      howToClaim: [
        'Verify your student credentials at education.github.com',
        'Click the Frontend Masters tile in the GitHub Student Developer Pack',
        'Log in to claim 6 months of 100% free streaming and learning paths',
      ],
      keyBenefits: [
        'Full access to 200+ comprehensive full-stack and architecture courses',
        'Download video lessons for offline learning on mobile apps',
        'Course completion certificates to showcase on LinkedIn and resume',
      ],
      eligibility: ['Enrolled students with verified GitHub Student Developer Pack'],
      isStudentDeal: true,
      isStartupDeal: false,
      needsCreditCard: false,
      isTrending: true,
      isLimitedTime: false,
    },
];
